server:
  port: 8082

kvstore:
  node-id: node2
  mode: leaderless
  role: node
  peers:
    - http://localhost:8080
    - http://localhost:8081
    - http://localhost:8083
    - http://localhost:8084
  quorum:
    write: 5
    read: 1
  delays:
    write-delay-ms: 200
    read-delay-ms: 50